export const UI_OPEN_DRAWER = 'UI_OPEN_DRAWER';
export const UI_CLOSE_DRAWER = 'UI_CLOSE_DRAWER';
export const UI_OPEN_FORM_ADDING_TASK = 'UI_OPEN_FORM_ADDING_TASK';
export const UI_CLOSE_FORM_ADDING_TASK = 'UI_CLOSE_FORM_ADDING_TASK';
export const UI_SET_IS_DRAGGING = 'UI_SET_IS_DRAGGING';